# Generated by Django 5.2 on 2025-08-20 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
