# Generated by Django 5.2 on 2025-08-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
